### ISSUE TITLE
diffusion routine not working...

### ISSUE THREAD

**Issue by adriantompkins** [brian-rose/ClimateModeling_courseware#4]
In lecture 16, the code for the diffusion doesn't appear to do anything.
d.step_forward() 
doesn't update Ts.  In both your plots and my offline runs of the code, the temperature remains fixed.

**Comment by brian-rose** [comment]
hmm... you are correct. This must have gotten broken by a climlab update at some point I never noticed.

Thanks, will look into this.

**Comment by brian-rose** [comment]
I think this is fixed as of 67e581fce34a2f12b8740fef99c96a1b9172356c.

The issue was that the diffusion solvers were improved at some point and the expected units for the input parameters were modified to be more consistent. 

See [the docs here](https://climlab.readthedocs.io/en/latest/api/climlab.dynamics.html) for more info.
