### ISSUE TITLE
Lecture 10 - missing data

### ISSUE THREAD

**Issue by geofffoster** [brian-rose/ClimateModeling_courseware#8]
links don't work - upon checking on server directory doesn't exist. Is it possible to put data in github?
In [4]
datapath = "http://thredds.atmos.albany.edu:8080/thredds/dodsC/cesm/"
ctrl = xr.open_dataset(datapath + 'som_control/som_control.cam.h0.clim.nc', decode_times=False)
co2 = xr.open_dataset(datapath + 'som_2xCO2/som_2xCO2.cam.h0.clim.nc', decode_times=False)

same for 
In [15]:
ozone = xr.open_dataset( datapath + 'som_input/ozone_1.9x2.5_L26_2000clim_c091112.nc')

**Comment by brian-rose** [comment]
Thanks, I'm not maintaining this repo anymore because all the content has been repackaged in [The Climate Laboratory](https://brian-rose.github.io/ClimateLaboratoryBook), which will be kept up-to-date.

However I think the same path errors exist in the [book version of those notes](https://brian-rose.github.io/ClimateLaboratoryBook/courseware/spectral-bands.html), which stems from some reorganization of our data servers. I will fix the book version.

**Comment by geofffoster** [comment]
HI Brian,thanks for the prompt response. Yes its in the book  as well.
Great set of lectures by the way - I've loved going through them
regards
Geoff
    On Sunday, 17 May 2020, 05:53:11 pm GMT+1, Brian Rose <notifications@github.com> wrote:  
 
 


Thanks, I'm not maintaining this repo anymore because all the content has been repackaged in The Climate Laboratory, which will be kept up-to-date.

However I think the same path errors exist in the book version of those notes, which stems from some reorganization of our data servers. I will fix the book version.

**Comment by brian-rose** [comment]
See the updated version in the book at https://brian-rose.github.io/ClimateLaboratoryBook/courseware/spectral-bands.html. All links now working.

**Comment by geofffoster** [comment]
Yes - its now working and will allow me to play with the inputs 
many thanksGeoff
    On Monday, 18 May 2020, 03:52:15 pm GMT+1, Brian Rose <notifications@github.com> wrote:  
 
 


See the updated version in the book at https://brian-rose.github.io/ClimateLaboratoryBook/courseware/spectral-bands.html. All links now working.
